"""empty message

Revision ID: 702e86a1f32c
Revises: cfc8881419ed
Create Date: 2021-12-07 21:42:19.833645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "702e86a1f32c"
down_revision = "cfc8881419ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo_url", sa.String(length=255), nullable=False),
        sa.Column("account", sa.Float(), nullable=False),
        sa.Column(
            "create_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "rejected", "approved", name="state"),
            nullable=False,
        ),
        sa.Column("complainer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complainer_id"],
            ["complainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complaints")
    # ### end Alembic commands ###
